In [38]:
import pandas as pd 
from pathlib import Path 

if Path("data/raw").exists():
    RAW = Path("data/raw")
else:
    RAW = Path(r"C:\Users\ravi3\Desktop\retail_practice\data\raw")

orders = pd.read_csv(RAW/"orders.csv")
customers = pd.read_csv(RAW/"customers.csv")
products  = pd.read_csv(RAW/"products.csv")
regions  = pd.read_csv(RAW/"regions.csv")
returns  = pd.read_csv(RAW/"returns.csv")
marketing  = pd.read_csv(RAW/"marketing_spend.csv")

print('orders:', orders.shape)
print('customers:', customers.shape)
print('products:', products.shape)
print('returns:', returns.shape)
print('marketing_spend:', marketing.shape)
orders.head()

orders: (59584, 13)
customers: (12000, 5)
products: (148, 5)
returns: (4614, 5)
marketing_spend: (1296, 4)

,order_id,order_date,customer_id,product_id,region_id,channel,quantity,unit_price,discount_pct,revenue,cost,gross_profit,quality_flag
0,1,2025-09-02,9872.0,130,6.0,Social,1,40.63,0.000,40.63,24.82,15.81,NaN
1,2,2025-08-19,10280.0,77,6.0,Paid Search,11,15.02,0.230,165.22,85.91,79.31,NaN
2,3,2025-01-14,1695.0,9,5.0,Affiliate,2,485.26,0.049,970.52,829.02,141.50,NaN
3,4,2025-08-25,1224.0,31,5.0,Paid Search,2,108.13,0.130,216.26,116.82,99.44,NaN
4,5,2025-08-03,8021.0,7,1.0,Paid Search,1,534.25,0.092,534.25,424.38,109.87,NaN

In [39]:
orders.dtypes

order_id          int64
order_date          str
customer_id     float64
product_id        int64
region_id       float64
channel             str
quantity          int64
unit_price      float64
discount_pct    float64
revenue         float64
cost            float64
gross_profit    float64
quality_flag        str
dtype: object

In [28]:
# 1. Count how many orders have a missing (NaN) customer_id

missing_customer = orders['customer_id'].isna().sum()
total_orders = len(orders)
pct_missing_cust = (missing_customer/total_orders)*100

print(f"Total missing customer = {missing_customer:,}")
print(f"Total orders = {total_orders:,}")
print(f"Percentage of total missing customer = {pct_missing_cust:.2f}%")

# 2. How much real money did these guest checkouts generate?

guest_orders = orders[orders["customer_id"].isna()]
guest_revenue = guest_orders["revenue"].sum()

print(f"Total revenue generated by the guest checkouts ${guest_revenue:,.2f}")
guest_orders.head()

Total missing customer = 1,847
Total orders = 59,584
Percentage of total missing customer = 3.10%
Total revenue generated by the guest checkouts $737,520.43

,order_id,order_date,customer_id,product_id,region_id,channel,quantity,unit_price,discount_pct,revenue,cost,gross_profit,quality_flag
28,29,2025-06-19,NaN,10,2.0,Social,1,711.72,0.050,711.72,557.54,154.18,NaN
81,82,2025-09-04,NaN,109,NaN,Social,1,7.49,0.119,7.49,7.09,0.40,NaN
83,84,2024-02-01,NaN,53,1.0,Organic,4,253.35,0.078,1013.40,621.32,392.08,NaN
85,86,2024-03-28,NaN,111,4.0,Paid Search,8,75.86,0.110,606.88,393.28,213.60,NaN
119,120,2025-11-24,NaN,34,NaN,Email,4,94.19,0.111,376.76,211.20,165.56,NaN

In [29]:
print(f"All unique channel names :")
print(orders["channel"].unique())

print(f"To get unique spelling variant:{orders['channel'].nunique()}")

All unique channel names :
<StringArray>
[     'Social', 'Paid Search',   'Affiliate',     'Organic',       'Email',
      'Direct',      'direct', 'Paid_Search',     'ORGANIC',   'AFFILIATE',
      'SOCIAL',     'organic',       'email',       'EMAIL',      'social',
      'DIRECT', 'paid search', 'PAID SEARCH',   'affiliate']
Length: 19, dtype: str
To get unique spelling variant:19

In [30]:
orders['channel'].value_counts()

channel
Paid Search    16433
Social         13346
Organic        10121
Email           5573
Affiliate       5531
Direct          4464
Paid_Search      568
PAID SEARCH      518
paid search      512
social           440
SOCIAL           390
ORGANIC          343
organic          317
email            200
AFFILIATE        187
affiliate        177
EMAIL            159
direct           154
DIRECT           151
Name: count, dtype: int64

In [31]:
bad_price = orders[orders['unit_price']<=0]
print(f"len of bad_price = {len(bad_price)}")
print(f"the glitched price found = {bad_price['unit_price'].unique()}")
bad_price[['order_id','product_id','unit_price','revenue','cost','gross_profit']].head(5)

len of bad_price = 187
the glitched price found = [-17.85902328   0.        ]

      order_id  product_id  unit_price  revenue    cost  gross_profit
161        162         115  -17.859023   -17.86  106.84         52.89
545        546         125    0.000000     0.00  101.18         57.88
875        876          98  -17.859023   -17.86    7.80          1.64
1288      1289          69    0.000000     0.00  607.50        250.08
1299      1300         100  -17.859023   -71.44   36.44          5.36

In [32]:
#bug 5 

# 1. Count how many orders have a blank (NaN) region_id:
missing_region = orders['region_id'].isna().sum()
total_len = len(orders)
pct_missing_region = (missing_region/total_len) * 100

print(f"total missing region:{missing_region:,}")
print(f"percentage of missing_region :{pct_missing_region:.2f}%")

# 2. How much revenue is trapped in these orders without a region?
trapped_revenue = orders[orders['region_id'].isna()]['revenue'].sum()
print(f"Total revenue trapped in the region is ${trapped_revenue:,.2f}")

# 3. Look at a few of these orders:
orders[orders['region_id'].isna()][['order_id','order_date','customer_id','revenue','region_id']].head(5)

total missing region:1,430
percentage of missing_region :2.40%
Total revenue trapped in the region is $579,142.71

     order_id  order_date  customer_id  revenue  region_id
16         17  2025-11-16       2048.0  1443.28        NaN
81         82  2025-09-04          NaN     7.49        NaN
118       119  2025-11-10       4256.0   531.98        NaN
119       120  2025-11-24          NaN   376.76        NaN
176       177  2024-11-30       7126.0  1846.05        NaN

In [33]:
#bug 6 
#return orders
returns.head()
#total number of Return orders
print(f"Total no of return orders = {len(returns):,.2f}")

returns.head(3)

Total no of return orders = 4,614.00

   return_id  order_id return_date            reason  refund_amount
0          1         8  2025-09-10      Changed mind         776.03
1          2        25  2025-01-09  Not as described         410.40
2          3        39  2025-03-01  Not as described          70.48

In [34]:
#match the return order and original order price 
return_with_orders = returns.merge(orders[['order_id','revenue']],on='order_id',how='left')

# 2. Find returns where the refund was GREATER than what they paid!
over_refunds = return_with_orders[return_with_orders['refund_amount'] > return_with_orders['revenue']]

# 3. Count how many times the cashier gave back too much money:
print(f"Total no of times the total amount > refund = {len(over_refunds):,.2f}")

# 4. Show the receipts side-by-side to catch the glitch:
over_refunds[['return_id','order_id','refund_amount','revenue']].head(5)

Total no of times the total amount > refund = 32.00

     return_id  order_id  refund_amount  revenue
94          95      1234          30.08    25.92
156        157      1952         276.40   240.06
159        160      2072          66.73    53.68
406        407      5104         328.25   282.64
856        857     11025          49.72    45.08

In [35]:
#bug7
# lets see where orders column is not equal to order id 
#lets just dropped the duplicate orders
campare_cols = [c for c in orders.columns if c != 'order_id']
clean_orders = orders.drop_duplicates(subset=campare_cols,keep='first')

#Are there any return receipts whose order_id is NOT inside clean orders?
orphaned_returns = returns[~returns['order_id'].isin(clean_orders['order_id'])]

#how many ghost returns exist
print(f"Total 'Ghost' returns that have no matching order: {len(orphaned_returns):,.2f}")    

orphaned_returns.head(5)

Total 'Ghost' returns that have no matching order: 25.00

      return_id  order_id return_date            reason  refund_amount
145         146      1838  2025-08-03      Changed mind          76.25
394         395      4917  2024-02-13         Defective         292.60
1190       1191     15254  2024-11-30  Not as described         202.93
1715       1716     21607  2024-04-04    Wrong size/fit         243.35
1858       1859     23488  2025-01-27      Changed mind         174.21

In [36]:
#bug 8 
#Calculate what Gross Profit SHOULD be (Revenue minus Cost), rounded to 2 decimal cents:
expected_profit = (orders['revenue'] - orders['cost']).round(2)
expected_profit

#Check if the recorded gross_profit matches what it should be!

math_mismatch = orders[
    (orders['unit_price'] > 0) &
    (orders['gross_profit'].round(2) != expected_profit)
    ]

print(f"Total orders with floating-point penny math drift = {len(math_mismatch):,.2f}")

Total orders with floating-point penny math drift = 0.00